print "True\t%s" % (True and True)
print "False\t%s" % (False and True)
print "False\t%s" % (1 == 1 and 2 == 1)
print "True\t%s" % ("test" == "test")
print "True\t%r" % (1 == 1 or 2 != 1)
print "True\t%r" % (True and 1 == 1)
print "False\t%r" % (False and 0 != 0)
print "True\t%s" % (True or 1 == 1)
print "False\t%s" % ("test" == "testing")
print "False\t%s" % (1 != 0 and 2 == 1)
print "True\t%s" % ("test" != "testing")
print "False\t%s" % ("test" == 1)
print "True\t%s" % (not (True and False))
print "False\t%s" % (not (1 == 1 and 0 != 1))
print "False\t%s" % (not (10 == 1 or 1000 == 1000))
print "False\t%s" % (not (1 != 10 or 3 == 4))
print "True\t%s" % (not ("testing" == "testing" and "Zed" == "Cool Guy"))
print "True\t%s" % (1 == 1 and not ("testing" == 1 or 1 == 0))
print "False\t%s" % ("chunky" == "bacon" and not (3 == 4 or 3 == 3))
print "False\t%s" % (3 == 3 and not ("testing" == "testing" or "Python" == "Fun"))
